### ISSUE TITLE
Greetings. A small review and questions, please :)

### ISSUE THREAD

**Issue by Aquarius-62** [perfect-things/perfect-home#108] opened 2020-10-08 11:39 UTC
Greetings.

I'm trying out your addin (Firefox 81.0.1 (64-bit) in Win10) as I am looking for something clean and easy to use that doesn't involve 'online' storage. According to the manifest.json, I have:

manifest_version: 2,
name: Perfect Home,
version: 0.11.1

Overall I like the way you have this set up, and hope that I can figure out some things. I have read through the 'issues' (both Open and Closed) and saw a couple that were similar but not the same.

The main issue that I am running across is the following:

I had removed all of my bookmarks and (through a very complex process) cleaned them up, resorted and re-folder'd them, then imported them back into Firefox. I did this after installing PH, so this is probably the reason this is screwed up :)

What I'm looking for is a way to 'reset' the addin without having to uninstall then reinstall it.

I noticed that the bookmarks folders that show in the lists in Settings (both for the Main and Docked folders) is not sorted and doesn't seem to update, not is there a way to 'refresh' the list.

Is there a 'cache' file somewhere in the install directory that can be either deleted or refreshed? If the folder list was stored in a text file (or something easily edited by a text editor) it would make this much easier as you could reorder or 'refresh' the folder names.

Thank you for your time and effort in doing this, I like the simpleness and neatness of this addin.

To make it (hopefully) easier to see what I am talking about, I have attached the screen snips that I just did:

The pics are:

Settings Menu

Settings and All Bookmarks

Empty Bookmarks Menu 'docked' folder

Using the Bookmarks Menu as the main screen (many folders shown)

Using the Bookmarks Toolbar as the main screen (only 1 folder, that folder will be my 'custom start folder' that I will have as my main start screen once I get my 'favorite' sites moved to there :) )

Using the custom 'start folder' as the main screen

Adding the Bookmarks Menu as 'docked' folder

Showing the Bookmarks Menu, empty

![PH-01](https://user-images.githubusercontent.com/58662818/95453189-044a7200-0930-11eb-870b-bc493ef085be.JPG)
![PH-02](https://user-images.githubusercontent.com/58662818/95453193-04e30880-0930-11eb-9c25-9a7106d1bc86.JPG)
![PH-03](https://user-images.githubusercontent.com/58662818/95453194-057b9f00-0930-11eb-92cf-ce46ff9317a5.JPG)
![PH-04](https://user-images.githubusercontent.com/58662818/95453196-057b9f00-0930-11eb-82e5-223bab240054.JPG)
![PH-05](https://user-images.githubusercontent.com/58662818/95453198-057b9f00-0930-11eb-9a5c-7bd6caef96a3.JPG)
![PH-06](https://user-images.githubusercontent.com/58662818/95453199-06143580-0930-11eb-8ef7-58061562438a.JPG)
![PH-07](https://user-images.githubusercontent.com/58662818/95453202-06143580-0930-11eb-9cee-4590a26a75b5.JPG)
![PH-08](https://user-images.githubusercontent.com/58662818/95453204-06accc00-0930-11eb-8e39-55321cae9ecd.JPG)

Thank you and have a great day :)

Aquarius-62

**Comment by tborychowski** [comment] 2020-10-08 22:06
Thanks for your comments.

So let me first try to answer your question about the cache reset:
- just click the bottom panel in settings, called "Reset", there you will find a "Clear cache" button that should purge all cache that the extension generates:
<img width="314" alt="Screenshot 2020-10-08 at 22 46 56" src="https://user-images.githubusercontent.com/392513/95517049-2ee00d80-09b8-11eb-95e9-6e743f0ab608.png">

However, this will not fix your "problem", as this clears the thumbnail cache and some settings.
The list of the folders that you have, in dropdowns is always loaded fresh, whenever you open the extension page (or reload the browser tab with the extension page open).

I think that the problem you have is with the way the docked folders work :-)

It is by design, that you don't see anything in your docked folder of "Bookmarks menu". Docked folders are intended to be flat, with no subfolders, only bookmarks (think: macos Dock, rather than Finder).
If I would allow folders there - there would have to be a complex navigation system devised to handle that:
- if you open a folder - should it be open in the same docked folder? 
- if so - we'd need breadcrumbs navigation
- if so - how should that be handled considering long folder names, etc.
- where's the back button
- how do we handle different sizes of folders (should it expand or remain fixed height/width), and in relation to browser window and other docked folders
- and much more.

I wanted to avoid all that, and remain simple to use and performant.
So - if you need folders - just add them **inside** your main folder.


Let me know if I didn't answer your questions :-).

Also, let me know what is the exact problem with sorting that you have (what do you mean that "folders are not sorted").

Thanks,
Tom

**Comment by Aquarius-62** [comment] 2020-10-09 14:46
Hi Tom, and thank you for the reply and explanations. Very clear and understandable 👍 

I'll comment specifically inline...

> 
>  just click the bottom panel in settings, called "Reset", there you will find a "Clear cache" button that should purge all cache that the extension generates:
> 
Ah, gotcha. Comes from not looking around enough <grin>
> 
> 
> However, this will not fix your "problem", as this clears the thumbnail cache and some settings.
> The list of the folders that you have, in dropdowns is always loaded fresh, whenever you open the extension page (or reload the browser tab with the extension page open).
> 
Ok, I think I've seen that, and that's not a problem 👍 

> I think that the problem you have is with the way the docked folders work :-)
> 
> It is by design, that you don't see anything in your docked folder of "Bookmarks menu". Docked folders are intended to be flat, with no subfolders, only bookmarks (think: macos Dock, rather than Finder).

I see now... I thought it was for more folders. That'll work fine, I just have to 're-adjust' my thinking.

> 
> Also, let me know what is the exact problem with sorting that you have (what do you mean that "folders are not sorted").

Ok, when I go to Settings, and the list of 'Folders' comes up (if I'm chosing either my Main folder or Docked folders), the folders listed are in random order (it looks like they are as they are created ?). It then takes time to go thropugh to find the folder name I'm looking for.

See new pics:

![PH-10](https://user-images.githubusercontent.com/58662818/95597175-ea825b00-0a13-11eb-91f0-44d6b69a3148.JPG)
![PH-09](https://user-images.githubusercontent.com/58662818/95597177-eb1af180-0a13-11eb-8704-90241b6c9f26.JPG)

If they were sorted in alpha order it'd be faster.

I appreciate the reply and the help... I like the addin. 

> 
> Thanks,
> Tom

Have a great weekend.

**Comment by Aquarius-62** [comment] 2020-10-09 15:21
Hi Tom.

Quick question: is there a way to either 'default' or set as 'default' to open ina  new tab or window?

Thanks.

**Comment by tborychowski** [comment] 2020-10-09 20:26
Hi @Aquarius-62 ,

Re: folders sort order:
Yes, it makes sense to sort them alphabetically. I'll add that to the task list (#109).

In the mean time - what you can try is: when you open the dropdown (because it's the native html select) you can use your keyboard to quickly find items, e.g.:
- in your list there is "Entertainment" folder - so when you start typing: `enter` using your keyboard - the select should highlight this folder. (you just need to type it rather quickly 😄)

Re: your other question (if I understand it correctly): once you install PerfectHome addon - it should overwrite your home page and newtab page and open on both by default.
In your firefox settings in the `Home` section, do you see sth. like this?

<img width="699" alt="Screenshot 2020-10-09 at 21 26 14" src="https://user-images.githubusercontent.com/392513/95628503-120a0f80-0a76-11eb-9393-656e6f8a10e0.png">

**Comment by Aquarius-62** [comment] 2020-10-10 03:02
Hi Tom, and thanks again.

I always have Firefox (or any other browser that I am using) open websites in a new tab or window, instead of opening in the same tab. 

Example: When I open Firefox, the PerfectHome tab (default Home) shows up. I click on one of my links, and it opens in the same tab. If I want to go back to my Home page, I then have to either click the Home button or go 'back' to it.

Before I installed PH, when I would click on one of the 'links' I had on my 'Home' page, it would automatically open in a new tab, which is how I have my browser set up.

Thanks again for the help. Have a great weekend :)

![image](https://user-images.githubusercontent.com/58662818/95644253-0d942580-0a7b-11eb-98cf-27484d8dbbf9.png)

**Comment by tborychowski** [comment] 2020-10-10 06:47
Ok, I misunderstood your question 😀

You want the links from the PerfectHome to open in a new tab. 

Unfortunately this isn't something that I'd like to implement. 
The reason is: 
- if you have a regular link - you have a choice to either open it in the same tab or in a new one
- if you have a link that only opens in a new tab - you don't have that choice. 

And having more choices is always better 😀

And it's just too easy to open links in a new tab:
- you can right-click it and select "open in a new tab"
- you can ctrl/cmd click
- you can click the middle mouse button (if your mouse has one)
- if you're using keyboard and the link has focus - ctrl/cmd + enter

So sorry about that, but from usability perspective it's much better to not force the user. 

The only way would be to add an option in settings: "always open links in a new tab".

**Comment by Aquarius-62** [comment] 2020-10-10 14:57
Hi Tom.

No problem, I was thinking about the option to be added so that they could be opened if that is 'my' choice, not forcing it.

I know this is a per-user preference. 

Keep up the good work...have a great weekend :)

**Comment by tborychowski** [comment] 2020-10-14 15:21
I've created a new issue for reference https://github.com/perfect-things/perfect-home/issues/110
and will close this one.
Thanks!

**Closed as completed by tborychowski** 2020-10-14 15:21 UTC
