### ISSUE TITLE
Bug: main folder does not reflect user-configured main folder

### ISSUE THREAD

**Issue by cengels** [perfect-things/perfect-home#79] opened 2020-04-02 11:20 UTC
## Actual behaviour

If the user sets the extension to use a different main folder, the folder is correctly set. If the user then closes and reopens the settings, the main folder is reset to "Bookmarks Menu," even if the actual main folder is now a different one.

As a side-effect, the only way to reset the main folder to "Bookmarks Menu" is to change it away from "Bookmarks Menu" and then back to "Bookmarks Menu." Trying to click "Bookmarks Menu" again does not change the main folder since it is already considered selected.

## Expected behaviour

When the user closes and reopens the settings, the main folder should correctly reflect the main folder.

**Comment by tborychowski** [comment] 2020-04-03 09:38
Hi,
Thanks for your contribution.
I really appreciate it.

Regarding the issue - it's weird, but I've never seen this issue happening to me.
I just tested that and it works correctly.
Can you let me know 2 things:
- what OS are you using?
- can you write all your actions in steps (from: "launching browser")

Also - what would really help is if you could record a gif/video with the issue and upload it here.

Thanks!

**Comment by cengels** [comment] 2020-04-03 10:04
Okay, I did some further testing and came to some bizarre conclusions.

First of all, I'm using Windows 10. Here are the steps after launching the browser:

1. open a new empty tab
2. click on the settings gear
3. main folder will be "Bookmarks Menu" rather then the folder shown in the main view

Here's what happens if you change the main folder:

1. change the main folder
2. close the settings menu
3. reopen the settings menu
4. the main folder is still correctly marked as the one I just set it as
5. reload the page (F5)
6. open the settings menu
7. the main folder is now incorrectly shown as "Bookmarks Menu"

I tried recording a video with these precise steps, but since I am uncomfortable with sharing all of my actual bookmarks, I tried doing so in a new Firefox profile with only the extension installed and some mock bookmarks.

Unfortunately, in that new profile the issue _**did not occur,**_ which I find kind of bizarre since there is otherwise no indication that anything is wrong with my browser configuration and this is clearly an issue with the data binding to that combo-box input field (which should be completely browser-agnostic). I also tried clearing the extension's cache from the settings menu in my "broken" profile, but that made no difference either.

When I have time, I'll do some more digging and try out a few other things (like disabling all other extensions and clearing my browser cache). I'll report on my findings once I've discovered something.

**Comment by cengels** [comment] 2020-04-03 13:14
I tried to reproduce the bug with

* all extensions disabled and
* the cache and cookies cleared

but it still happened. I *did* stumble upon [this StackOverflow post](https://stackoverflow.com/questions/4831848/firefox-ignores-option-selected-selected) which sounds _somewhat_ like my issue and offers some solutions, but I'm not sure that's it since there's obviously something inside my user profile that's causing it.

At this point I am sort of at a loss. Perhaps I'll try cloning the repo, applying some of the fixes in that StackOverflow post, and seeing if any of them make it work.

**Comment by tborychowski** [comment] 2020-04-04 01:04
The link to SO is missing from your comment. Would you mind adding it, so I can see what you mean?

**Comment by cengels** [comment] 2020-04-04 05:47
Oops. Not sure what happened there. Fixed now.

**Comment by cengels** [comment] 2020-04-13 10:06
I did some more testing and can happily report that I have successfully identified the issue.

The cause of the issue appears to be the scrollability of the main folder dropdown. If the user has sufficiently few bookmark folders that the main folder dropdown is not long enough to warrant a scrollbar, the main folder is always properly set when refreshing the page. However, as soon as a scrollbar appears inside the dropdown, the main folder will show "Bookmarks Menu," regardless of what it is set to.

Hopefully this will help you diagnose the issue further and perhaps even reproduce it. I was able to consistently reproduce the issue in a clean Firefox Nightly user profile. If you can't reproduce it, I would be happy to record a short video showcasing it.

**Comment by tborychowski** [comment] 2020-04-13 14:47
Thanks for testing. I really appreciate it.
Unfortunately I can't reproduce it.
Would it be possible for you to check a stable version of firefox? 
Nightly versions are usually not very stable have bugs.
(I'm not saying that this is firefox bug, and my extension is fine, but just want to exclude other factors.)
I'm gonna download nightly as well just to make sure.
And - if it's still the problem in stable version, than I'd appreciate if you could post a video/gif (just to make sure I follow your steps exactly).
Thanks again!

**Comment by cengels** [comment] 2020-04-13 15:21
I must apologize for my previous post. There is a reason you weren't able to reproduce the problem: there were additional conditions that had to be met for the bug to appear. I had inadvertently included those conditions in my earlier tests. I now retested it and have identified all the conditions necessary and uploaded a video that showcases them all.

I also tested it in the stable version of Firefox and was able to reproduce it there as well.

There are 3 conditions necessary to make the bug appear:

* The bookmarks folder dropdown must be scrollable.
* The main page must be scrollable.
* It is not enough for only the main page of the main folder to be scrollable. I wasn't able to discover exactly how many folders need to have enough bookmarks to be scrollable when you click on them, but if only the selected main folder is scrollable, that is insufficient. In the video below, I duplicate one folder with enough bookmarks to be scrollable over and over.

[This](https://streamable.com/4uhg7s) is the video. I go through all the conditions one-by-one to prove that all of them have to be met for the bug to appear, and that it is not enough if only a part of the conditions above are met. To open Firefox's bookmarks menu, I use `CTRL+Shift+B`. To copy and paste bookmarks and bookmark folders, I use `CTRL+C` and `CTRL+V`. To refresh the page, I use `F5`.

I hope this helps.

**Comment by tborychowski** [comment] 2020-04-13 15:22
I've tested it in Firefox nightly and there is something weird with the dropdown as you described!

**Comment by tborychowski** [comment] 2020-04-13 15:35
Now I've got it! :-)
I can finally reproduce it!
I cannot thank you enough for such a thorough testing!

**Comment by tborychowski** [comment] 2020-04-13 15:52
turns out that's svelte's (framework that I'm using) rendering race condition.
settings were loaded before the dropdown finished rendering...
anyway that's fixed now (will be available in the next release probably today).

**Closed as completed** 2020-04-13 15:53 UTC
Labels: type:bug, priority:medium, size:M

**Comment by tborychowski** [comment] 2020-04-13 17:02
This should be fixed in the latest version 0.10.0.
Please reopen the issue if you still see the problem.
